version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/dhparam:/etc/nginx/dhparam
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
   
  nginx-proxy-certs:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-certs
    volumes:
      - ./nginx/certs:/etc/nginx/certs:rw
      - ./nginx/acme.sh:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
   
networks:
  default:
    external:
      name: web
  web:
    external: true